[package]
name = "wuwa-downloader"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
reqwest = { version = "0.12.15", features = ["blocking", "json"] }
serde_json = "1.0"
md-5 = "0.10"
ctrlc = "3.2"
shellexpand = "3.1.0"
winconsole = "0.11"